name: Build and Push visa-rate App

on:
  push:
    branches:
      - main # Cambia la rama si es necesario
    paths:
      - 'exchanges/**'
      
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      # Checkout del repositorio
      - name: Checkout repository
        uses: actions/checkout@v2

      # Set Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Log in to GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build the Docker image
      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository }}/visa-rate:${{ github.sha }} exchanges

      # Push the Docker image to GitHub Container Registry
      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.repository }}/visa-rate:${{ github.sha }}
